---
title: "Laboratorio de Bioestatística"
author: "Group 3"
date: "28 de Dezembro de 2019"
output:
  html_document:
    highlight: tango
    theme: united
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: no
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r}
library(here)
library(data.table)
library(unglue)
library(ggplot2)
library(magrittr)

data <- fread(here("CancerMortalityEU.csv"), 
              header = TRUE, check.names = TRUE)
popdt <- fread("PopulationEU.csv",
               header = TRUE, check.names=TRUE)
```

# Data Tidying 

## Cancer data

```{r cancerData, results= FALSE}
# Colunas certas nos dados
names(data)

cancro <- data[CancerSite %in% "Liver and Intrahepatic Bile Ducts"]


str(cancro)
cancro[, .N, by="CancerSite"] #Pode-se tirar esta coluna
cancro[, .N, by="Cause"] #Pode-se tirar esta coluna mas a ver se não se perde a informação
cancro[, .N, by="ageStart"] #Acho que se pode tirar também
cancro[, .N, by="ageLabel"] #Também acho que se pode tirar se bem que esta pode ser util à frente
cancro[, c("CancerSite", "Cause", "ageStart", "ageLabel"):=NULL]
setnames(cancro, "ageGroup", "Age")


# melt dos dados do cancro

cancer.new <- melt(cancro,
                   id.vars = c("Country","Age"),
                   variable.name = "all",
                   value.name = "Deaths")

cancer.new[, `:=` (Year=as.numeric(gsub("[^[:digit:].]",
                            "", all)))]

cancer.new[, Sex:=as.character(unglue_vec(all,"{x}_{y}",var="x"))]

cancer.new[, .N, by="Year"]
cancer.new[, .N, by="Sex"]
cancer.new[, all:=NULL]
setcolorder(cancer.new, c("Country","Age","Sex","Year","Deaths"))

# Criação do EU

cancer.EU <- cancer.new[, .(Country = "European Union", Deaths = sum(Deaths, na.rm = TRUE)), by = .(Year, Sex, Age)]
setcolorder(cancer.EU, c("Country","Age","Sex","Year","Deaths"))
cancer.liver <- rbind(cancer.new,cancer.EU)

# Criação do all

allAge <- cancer.liver[, .(Age = "All", Deaths = sum(Deaths, na.rm = TRUE)), by = .(Country, Year, Sex)]
setcolorder(allAge, c("Country", "Sex", "Age", "Year", "Deaths"))
cancer.liver <- rbind(cancer.liver,allAge)

# Selecting the important countries

cancer.liver <- cancer.liver[Country %in% c("Austria", "Cyprus", "Germany", "Malta", "Portugal", "European Union")
                             ][order(Year, Country)]

```


## Population Data

```{r dtPop, results= FALSE}
# Importing data
library(data.table)
popdt <- fread("PopulationEU.csv",
               header = TRUE, check.names=TRUE)

# Removing ageStart and ageLabel columns
popdt[, c("ageStart","ageLabel","X2000","X2001","X2002","X2003","X2004","X2005","X2006","X2007","X2008","X2009","X2010"):=NULL]

# Renaming ageGroup column to Age
setnames(popdt, c("ageGroup"),
                c("Age"))

# Morphing to long format
popT <- melt(popdt,
            id.vars = c("Country", "Sex", "Age"),
            measure = patterns("^X"),
            variable.name = "YearX",
            value.name = c("Population"),
            na.rm = TRUE)

# Year as numeric, removing YearX
popT[, `:=` (Year=as.numeric(gsub("[^[:digit:].]",
                            "", YearX)))][, YearX := NULL]
setcolorder(popT, c("Country", "Sex", "Age", "Year", "Population"))

# Removing rows for total population data 
#Seeing as we are treating females and males differently, the rows regarding total population info will not be used and should be removed.

popT <- popT[Sex != "Total"]

# Creating European Union as "Country"
#EU's population is the sum of the populations for each country, by year and age group

popEU <- popT[, .(Population = sum(Population, na.rm = TRUE)), by = .(Year, Sex, Age)][, Country := "European Union"]
setcolorder(popEU, c("Country", "Sex", "Age", "Year", "Population"))
pop <- rbind(popT, popEU)
pop <- pop[order(Year, Country)]

# Creating age group category "All", combining all ages
allAge <- pop[, .(Age = "All", Population = sum(Population, na.rm = TRUE)), by = .(Country, Year, Sex)]
setcolorder(allAge, c("Country", "Sex", "Age", "Year", "Population"))
allAge <- allAge[order(Year, Country)]

# Merging pop and allAge
pop <- rbind(pop, allAge)
pop <- pop[order(Year, Country, Sex)]

# Selecting only the countries in study
popF <- pop[Country %in% c("Austria", "Cyprus", "Germany", "Malta", "Portugal", "European Union")]
popF <- popF[order(Year, Country)]

popF
```

## Merging of the two data sets

```{r final data set}
data.f <- cancer.liver[popF, on=c("Country","Age","Sex","Year")]
data.f[, mrate := 100000*Deaths/Population]
data.f[Age %in% "All"][Sex %in% "Females"][, sum(Deaths, na.rm = TRUE), by=Country]
```


#End of the Great Tyiding

# First Question 

What are the time trends in the mortality rates between countries for all age groups (“All”) combined ?
– How do they compare with the European Union overall?

```{r Time trends for females}
data.f[Age %in% "All"][Sex %in% "Females"] %>% 
  ggplot(aes(Year,mrate, group=Country, colour = Country))+
    geom_point()+
    geom_line()+
    ggtitle("Time trends of Liver Cancer on the Female population")+
    ylab("Mortality Rate")
    
```

```{r Time trends for males}
data.f[Age %in% "All"][Sex %in% "Males"] %>% 
  ggplot(aes(Year,mrate, group=Country, colour = Country))+
    geom_point()+
    geom_line()+
    ggtitle("Time trends of Liver Cancer on the Male population")+
    ylab("Mortality Rate")
```


# Second question

Compare the mortality rates by age groups between countries for 2017.

```{r}
data.f[Sex %in% "Females"] %>%
  ggplot(aes(Year,mrate, group=Country))+
    geom_line()+
    facet_wrap(~Age)
```













